<!-- rmd lab header -->

```{r,include=FALSE,cache=FALSE}
# load libraries
library(knitr) # runs pandoc
library(bookdown) # for markdown
library(captioner) # for table and figure captions
library(fontawesome) # icons

# fontawesome dependency
fa <- rmarkdown::html_dependency_font_awesome()
fa$attachment <- "fonts/fontawesome-webfont.ttf"
htmltools::tagList(fa)

# prepare captions
tc <- captioner::captioner(prefix="<b>Tab. </b>")
fc <- captioner::captioner(prefix="<b>Fig. </b>")

# turn off terminal colors
options(crayon.enabled = FALSE)

# knitr options
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
knitr::opts_chunk$set(dev="png",fig.retina=2,results="hold",fig.show="hold",fig.align="left",
                      echo=TRUE,warning=FALSE,message=FALSE,accordion=NULL,
                      chunk.title=NULL)
color_primary <- "#95b540"
color_text <- "#424949"
```

```{r,include=FALSE,cache=FALSE}
# custom hooks
## collapsible panel
knitr::knit_hooks$set(accordion=function(before,options,envir) {
  if(before) {
    id <- paste0("acc",format(Sys.time(),"%Y%m%d%H%S"),sample(c(0:9),1),sample(c(0:9),1),sample(c(0:9),1),sample(c(0:9),1))
    if(is.null(options$btn.type)) {btn.type <- "normal"}else{btn.type <- options$btn.type}
    paste0('<p>',
          '<button class="btn btn-sm btn-primary btn-collapse btn-collapse-',btn.type,' collapsed" type="button" data-toggle="collapse" data-target="#',id,'" aria-expanded="false" aria-controls="',id,'">',
          '</button>',
          '</p>',
          '<div class="collapse" id="',id,'">',
          '<div class="card card-body">')
  }else{
    paste0("</div>","</div>")
  }
})

## blur panel
knitr::knit_hooks$set(blur=function(before,options,envir) {
  if(before) {
    if(is.null(options$blur.title)) {blur.title <- ""}else{blur.title <- options$blur.title}
    paste0('<div class="blur-outer">',
           '<div class="blur-title">',blur.title,'</div>',
           '<div class="blur-content">')
  }else{
    paste0("</div>","</div>")
  }
})

## chunk.title for code
knitr::knit_hooks$set(chunk.title=function(before,options,envir) {

out_class <- NULL
if(is.null(options$class.output)) {
if(options$echo) out_class <- options$engine
if((!options$echo) & (options$results != "hide")) out_class <- "Output"
}else{
  out_class <- options$class.output
}

  if(before) {
    paste0('<div class="chunk-title-parent"><div class="chunk-title small">',out_class,'</div>')
  }else{
    paste0('</div>')
  }
})

# knit engine output

eng_output <- function(options) {
  out <- ''
  engine_output(options, options$code, out)
}

knitr::knit_engines$set(output=eng_output)

# custom fontawesome fa function
fa1 <- function (name=NULL,style="height:0.8em;top:0.04em;position:relative;fill:#424949;",extra_style=NULL)
{
    full_name <- NULL
    if (name %in% fontawesome:::fa_tbl$full_name) {
        svg <- fontawesome:::fa_tbl[which(fontawesome:::fa_tbl$full_name == name), ][1, 4]
    }
    else if (name %in% fontawesome:::fa_tbl$name) {
        svg <- fontawesome:::fa_tbl[which(fontawesome:::fa_tbl$name == name), ][1, 4]
    }
    else {
        return("")
    }

    if(!is.null(extra_style)) style <- paste0(style,extra_style)
    style <- paste0("style=\"", style, "\"")

    if (!grepl(style, pattern = "style=\"\"")) {
        svg <- gsub(pattern = "^<svg", replacement = paste0("<svg ",
            style), x = svg)
    }
    svg <- htmltools::HTML(svg)
    class(svg) <- c("fontawesome", class(svg))
    return(paste0("<span>",svg,"</span>"))
}

fa2 <- function(name=NULL,style="height:0.8em;top:0.04em;position:relative;fill:white;margin-left:0.45em;margin-bottom: 0.1em;") {
  return(fa1(name,style))
}
```

<br>
